- name: Make sure path exists
  file: path=~/tmp/docker state=directory mode=0755
  delegate_to: localhost

- name: Tar the docker image of jupyterhub
  command: docker save -o "{{ jupyterhub_images.local_dir }}" jupyterhub_jupyterhub
  when: recreate_images == "true"
  delegate_to: localhost

- name: Tar the docker image of the specific notebook
  command: docker save -o "{{ custom_notebook_images.local_dir }}" jupyterhub_custom_notebook
  when: recreate_images == "true"
  delegate_to: localhost

- name: Copy docker jupyterhub image to hosts
  copy: src={{ jupyterhub_images.local_dir }} dest={{ jupyterhub_images.remote_dir }}
  when: recreate_images == "true"

- name: Copy docker notebook image to hosts
  copy: src={{ custom_notebook_images.local_dir }} dest={{ custom_notebook_images.remote_dir }}
  when: recreate_images == "true"

- name: Load jupyterhub docker image into the docker daemon
  docker_image:
    name: jupyterhub_jupyterhub
    state: present
    load_path: "{{ jupyterhub_images.remote_dir }}"
  when: recreate_images == "true"

- name: Load notebook docker image into the docker daemon
  docker_image:
    name: jupyterhub_custom_notebook
    state: present
    load_path: "{{ custom_notebook_images.remote_dir }}"
  when: recreate_images == "true"

- name: Create the docker network
  docker_network:
    name: "{{ jupyterhub_envs.DOCKER_NETWORK_NAME }}"

- name: Start the jupyterhub container
  docker_container:
    name: jupyterhub
    restart_policy: on-failure
    image: jupyterhub_jupyterhub
    keep_volumes: yes
    restart: yes
    state: started
    env: "{{ jupyterhub_envs }}"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "data:/data"
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    networks:
      - name: "{{ jupyterhub_envs.DOCKER_NETWORK_NAME }}"
  become: true
