- name: copy the key to install docker
  copy: src=files/yum_docker.repo dest=/etc/yum.repos.d/docker.repo
  become: yes
  become_user: root

# Install docker-engine on the remote machine
- name: Install docker engine
  yum:
    name: docker-engine
    state: present
  become: yes
  become_user: root

- meta: flush_handlers

- name: install python-pip
  yum:
    name: python-pip
    state: present
  become: yes
  become_user: root

- name: update pip
  pip:
    name: pip
    state: latest
  become: yes
  become_user: root

- name: install docker-py
  pip: name=docker-py
  become: yes
  become_user: root


 #Add user to docker group
- name: add user to the docker group
  user:
   name: "{{ansible_user_id}}"
   shell: /bin/bash
   groups: docker
   append: yes
  become: yes
  become_user: root

- name: add additional users to the docker group
  user:
   name: "{{item}}"
   shell: /bin/bash
   groups: docker
   append: yes
  become: yes
  become_user: root
  with_items: "{{users_for_docker_group}}"
  when: users_for_docker_group is defined

# Install docker-compose on the remote machine
- name: Install docker compose
  pip:
    name: docker-compose
    version: "{{docker_compose_version}}"
  become: yes
  become_user: root
  tags: docker_compose
