VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.memory = 2048
    config.cpus = 2
    config.vm.box = "centos/7"
    config.vm.network "forwarded_port", guest: 443, host: 8443
end