# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Pin to version of notebook image that includes start-singleuser.sh script
FROM jupyter/scipy-notebook:latest

RUN pip install pip --upgrade
# Install packages in default Python 3 environment
RUN pip install \
  beautifulsoup4==4.4.* \
  xgboost==0.6a2

# R notebook
RUN conda install -c r r-essentials
