- name: Download python pip
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: /etc/get-pip.py
    mode: 0440
  become: yes
  become_user: root

- name: Install python pip
  command: python /etc/get-pip.py
  become: yes
  become_user: root

- name: Add repository to install docker
  yum_repository:
    name: epel
    description: Docker Repository
    gpgcheck: yes
    enabled: true
    gpgkey: https://yum.dockerproject.org/gpg
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
  become: yes
  become_user: root

- name: Install docker engine
  yum:
    name: docker-engine
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: Enable docker service
  command: systemctl enable docker.service
  become: yes
  become_user: root

- name: Start docker service
  command: systemctl start docker
  become: yes
  become_user: root

- name: update pip
  pip:
    name: pip
    state: latest
  become: yes
  become_user: root

- name: install docker-py
  pip: name=docker-py
  become: yes
  become_user: root

 #Add user to docker group
- name: add user to the docker group
  user:
   name: "{{ansible_user_id}}"
   shell: /bin/bash
   groups: docker
   append: yes
  become: yes
  become_user: root

- name: add additional users to the docker group
  user:
   name: "{{item}}"
   shell: /bin/bash
   groups: docker
   append: yes
  become: yes
  become_user: root
  with_items: "{{users_for_docker_group}}"
  when: users_for_docker_group is defined

# Install docker-compose on the remote machine
- name: Install docker compose
  pip:
    name: docker-compose
    version: "{{docker_compose_version}}"
  become: yes
  become_user: root
  tags: docker_compose
